### ISSUE TITLE
Routes don't properly handle accept params in the body with boolean types, which breaks swagger

### ISSUE THREAD

**Issue by jskrzypek** [strongloop/loopback-swagger#36] opened 2016-04-10 09:58 UTC
I've caught an error in how the rest connector interacts with the explorer that fails in a pretty bad way (i.e. hard to debug). I created an example repo here: https://github.com/jskrzypek/broken-rest-booleans.

On a separate note, looking at it again, I might be doing something wrong in how I'm building my rest connector operations.  I see now that the ui in the working case in my example is only taking the last body param as the body itself, rather than including all of the body params. Is this the intended behavior? Should I only have one `data` body param? ( as per the `HACK` on https://github.com/strongloop/loopback-swagger/blob/master/lib/specgen/route-helper.js#L279 )

**Comment by richardpringle** [comment] 2016-08-11 18:33
Hey @jskrzypek,

I think the issue is your baseUrl for the rest1 datasource (configured in datasource.json). 

loopback-connector-rest is meant for connecting to 3rd party REST services. You should have something that looks more like this: `https://maps.googleapis.com/maps/api/`.

I'm going to close the issue for now (since it took forever for us to get back to you) but please re-open it and mention me in a comment if your problems persist!

**Closed by richardpringle** 2016-08-11 18:33 UTC
